Options:
  # High, Normal, Low
  Running-Performance: Normal
  Multi-Thread: true
  Async-Load-Menus: true

Database:
  # LOCAL, MONGODB
  Method: LOCAL
  Url:
    Client: 'mongodb://localhost:3307'
    Database: trixey
    Collection: menu

Loader:
  Menu-Files:
    - 'plugins/CustomMenusFolder'

Menu:
  Settings:
    Bound-Item-Interval: 2000
  Icon:
    Inherit: false
    Item:
      Default-Name-Color: "&7"
      Default-Lore-Color: "&7"
      Pre-Color: false

Action:
  Inputer:
    Cancel-Words:
      - 'cancel|quit|end'
      - 'q'

Shortcuts:
  Offhand: [ ]
  Sneaking-Offhand:
    - condition: 'perm *trmenu.shortcut'
      execute: 'open: Example'
      deny: 'return'
  Right-Click-Player: 'open: Profile'
  Sneaking-Right-Click-Player: [ ]
  PlayerInventory-Border-Left: [ ]
  PlayerInventory-Border-Right: [ ]
  PlayerInventory-Border-Middle: [ ]

RegisterCommands:
  openMenus:
    aliases: [ ]
    permission: null
    execute:
      - 'tell: &7Argument `example` Required!'
    arguments:
      example: 'open: example'
