blank_issues_enabled: false
contact_links:
  - name: Discord server
    url: https://discord.gg/Fs6fJN3jXj
    about: InsinuateProjects's Discord
  - name: TrMenu wiki
    url: https://trmenu.trixey.cc/v/chinese/
    about: Official wiki of TrMenu(Only chinese now)